### PR TITLE
feat(route): ✨ Add Pronounce Route to API

### PR DESCRIPTION
**Pull request by mskian**
- Get Pronunciation for a Word - `http://localhost:3000/pronounce/hello%20world`
- Proper Error Page Validation

### CODE REVIEW

**Comment by mcnaveen** [comment]
Thanks @mskian
This looks amazing. I have a suggestion.

How about keeping the endpoint more easily accessible like this?

```
http://localhost:3000/pronounce/hello%20world
```

This will make the endpoint separate from the `/word`

What do you think?

**Comment by mskian** [comment]
looks clean
few mins Push the update

**Comment by mcnaveen** [comment]
@mskian I modified this PR to get the word via POST instead of the GET method.

This gives users more flexibility to send a larger paragraph.

**Comment by mskian** [comment]
@mcnaveen ok for me
I add extra validations for API data posting 
Move `proxy.js`, `test.js` and `api.rest` to test folder

**Comment by mcnaveen** [comment]
Sweet. LGTM ❤️ 🎉

**Pull request merged**
